repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort .
        types: [python]
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: black .
        types: [python]
      - id: pylint
        name: pylint
        stages: [commit]
        language: system
        entry: pylint gitmirror
        types: [python]
        pass_filenames: false
      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: flake8 gitmirror
        types: [python]
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: mypy gitmirror
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest --cov gitmirror
        types: [python]
        pass_filenames: false
