[tool.black]
exclude="venv/*"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.pylint.master]
load-plugins ="pylint.extensions.docparams, pylint.extensions.docstyle, pylint.extensions.mccabe"
jobs=4

[tool.pylint.basic]
good-names=["i", "e", "s3", "logger", "pd", "db", "df", "dt"]

[tool.pylint.format]
max-line-length = 88

[tool.pylint.message_control]
disable = [
    'line-too-long',
    'import-error',
    'docstring-first-line-empty',
    'logging-fstring-interpolation',
    'too-few-public-methods',
    'trailing-whitespace',
    'missing-return-type-doc',
    'missing-type-doc',
    'R0801',
    'C0115',
    'C0114'
]
